name: 'Automatic build'
on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

jobs:
  continuous-delivery:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # for posts's lastmod

      - name: Setup mdbook
        run: |
          wget https://github.com/rust-lang/mdBook/releases/download/v0.4.14/mdbook-v0.4.14-x86_64-unknown-linux-gnu.tar.gz
          tar -zxvf mdbook-v0.4.14-x86_64-unknown-linux-gnu.tar.gz -C /usr/local/bin

      - name: Build Book
        run: |
          mdbook clean
          mdbook build

      - name: Deploy
        run: |
          bash tools/deploy.sh
